### ISSUE TITLE
500 error recieved when conducting a search

### ISSUE THREAD

**Issue by avatar382** [archivesspace-plugins/lcnaf#4]
When executing a search via the LCNAF plugin, the search fails with an error dialog "Search Error", with text that indicates a 500 error being received from the remote server.

The log output on the ArchiveSpace side is showing the following:

```
I, [2018-12-24T20:37:43.561732 #1101]  INFO -- : Completed 500 Internal Server Error in 223ms
F, [2018-12-24T20:37:43.570923 #1101] FATAL -- :
F, [2018-12-24T20:37:43.571381 #1101] FATAL -- : OpenSearcher::OpenSearchException (Error during OpenSearch search: <!DOCTYPE html>
<html>
  <head>
    <title>418 I'm a teapot. Slow down, cap'n. Have some tea and enjoy the dulcet tones of Rick Astley.</title>
  </head>
  <body>
    <h1>Error 418 I'm a teapot. Slow down, cap'n. Have some tea and enjoy the dulcet tones of Rick Astley.</h1>
    <p>I'm a teapot. Slow down, cap'n. Have some tea and enjoy the dulcet tones of Rick Astley.</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 17981510</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
):
F, [2018-12-24T20:37:43.571572 #1101] FATAL -- :
F, [2018-12-24T20:37:43.571778 #1101] FATAL -- : /var/www/scu/plugins/lcnaf/frontend/models/opensearcher.rb:78:in `block in search'
```

Here are screenshots of the error from the ArchivesSpace side:

<img width="706" alt="screen shot 2018-12-24 at 3 51 27 pm" src="https://user-images.githubusercontent.com/130926/50406511-293e1700-0794-11e9-89f8-f4c5835a0cf6.png">
<img width="347" alt="screen shot 2018-12-24 at 3 51 18 pm" src="https://user-images.githubusercontent.com/130926/50406512-2cd19e00-0794-11e9-9f9d-97878f6355e5.png">

I've replicated this problem with different instances of ArchivesSpace, versions 2.2.1 to 2.5.1, and with LCNAF, LCSH, and OCLC searches.

Is there further configuration that needs to be done with the plugin, or is this a problem with the search providers themselves?

**Comment by lmcglohon** [comment]
We believe that the issue is blacklisted IP addresses. As a workaround, in the archivesspace.sh script add -Djava.net.preferIPv6Addresses=true to the end of the string built for JAVA_OPTS.

**Comment by avatar382** [comment]
Thanks @lmcglohon! Adding the  -Djava.net.preferIPv6Addresses=true option to archivesspace.sh resolved the problem for me.
